"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 10:14:49.400961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_timezone', sa.String(length=64), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('branches',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_branches_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_branches_organization_id_code'))
    )
    op.create_index(op.f('ix_branches_organization_id'), 'branches', ['organization_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('LATE_EMPLOYEE', 'SUSPICIOUS_CHECK_IN', 'REJECTED_CHECK_IN', 'MISSING_CHECKOUT', 'HIGH_ABSENCE', 'REPORT_GENERATED', 'DEVICE_APPROVAL_REQUESTED', name='event_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', name='channel', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('recipient_roles', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notification_settings_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_settings')),
    sa.UniqueConstraint('organization_id', 'event_type', 'channel', name=op.f('uq_notification_settings_organization_id_event_type_channel'))
    )
    op.create_table('retention_settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('data_category', sa.Enum('ATTENDANCE', 'RAW_LOCATION', 'SECURITY_EVENTS', 'AUDIT_LOGS', 'REPORT_FILES', 'NOTIFICATIONS', name='data_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('retain_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('retain_days >= 30', name=op.f('ck_retention_settings_retain_days_min')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_retention_settings_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_settings')),
    sa.UniqueConstraint('organization_id', 'data_category', name=op.f('uq_retention_settings_organization_id_data_category'))
    )
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', 'HR', 'ADMIN', name='role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('failed_login_count >= 0', name=op.f('ck_users_failed_login_count_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('work_schedules',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('early_departure_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('early_departure_minutes BETWEEN 0 AND 240', name=op.f('ck_work_schedules_early_departure_minutes_range')),
    sa.CheckConstraint('grace_minutes BETWEEN 0 AND 240', name=op.f('ck_work_schedules_grace_minutes_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_work_schedules_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_schedules')),
    sa.UniqueConstraint('organization_id', 'name', name=op.f('uq_work_schedules_organization_id_name'))
    )
    op.create_index(op.f('ix_work_schedules_organization_id'), 'work_schedules', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    sa.UniqueConstraint('seq', name=op.f('uq_audit_logs_seq'))
    )
    op.create_index('ix_audit_logs_actor_time', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_object', 'audit_logs', ['object_type', 'object_id'], unique=False)
    op.create_table('departments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_departments_branch_id_branches')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_departments_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_departments_organization_id_code'))
    )
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_table('locations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('radius_m', sa.Integer(), server_default='200', nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('work_schedule_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_locations_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_locations_longitude_range')),
    sa.CheckConstraint('radius_m BETWEEN 10 AND 5000', name=op.f('ck_locations_radius_range')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_locations_branch_id_branches')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_locations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], name=op.f('fk_locations_work_schedule_id_work_schedules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('organization_id', 'code', name=op.f('uq_locations_organization_id_code'))
    )
    op.create_index(op.f('ix_locations_branch_id'), 'locations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_table('managers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_managers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_managers')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_managers_employee_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_managers_user_id'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('LATE_EMPLOYEE', 'SUSPICIOUS_CHECK_IN', 'REJECTED_CHECK_IN', 'MISSING_CHECKOUT', 'HIGH_ABSENCE', 'REPORT_GENERATED', 'DEVICE_APPROVAL_REQUESTED', name='event_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('report_settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'EMPLOYEE', 'LOCATION', 'DEPARTMENT', 'MANAGER', 'LATE', 'ABSENCE', 'SUSPICIOUS', name='report_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('formats', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('recipient_roles', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('extra_recipients', postgresql.ARRAY(sa.String(length=320)), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('include_location_details', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_report_settings_created_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_report_settings_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_settings'))
    )
    op.create_index(op.f('ix_report_settings_organization_id'), 'report_settings', ['organization_id'], unique=False)
    op.create_table('work_schedule_days',
    sa.Column('work_schedule_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_work_schedule_days_end_after_start')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_work_schedule_days_weekday_range')),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], name=op.f('fk_work_schedule_days_work_schedule_id_work_schedules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_schedule_days')),
    sa.UniqueConstraint('work_schedule_id', 'weekday', name=op.f('uq_work_schedule_days_work_schedule_id_weekday'))
    )
    op.create_table('attendance_policies',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('verification_mode', sa.Enum('GPS_ONLY', 'GPS_QR', 'GPS_QR_PLUS', name='verification_mode', native_enum=False, create_constraint=True, length=32), server_default='GPS_ONLY', nullable=False),
    sa.Column('on_mock_location', sa.Enum('ALLOW', 'FLAG', 'REJECT', name='on_mock_location', native_enum=False, create_constraint=True, length=32), server_default='FLAG', nullable=False),
    sa.Column('on_integrity_fail', sa.Enum('ALLOW', 'FLAG', 'REJECT', name='on_integrity_fail', native_enum=False, create_constraint=True, length=32), server_default='FLAG', nullable=False),
    sa.Column('on_poor_accuracy', sa.Enum('ALLOW', 'FLAG', 'REJECT', name='on_poor_accuracy', native_enum=False, create_constraint=True, length=32), server_default='FLAG', nullable=False),
    sa.Column('on_stale_location', sa.Enum('ALLOW', 'FLAG', 'REJECT', name='on_stale_location', native_enum=False, create_constraint=True, length=32), server_default='FLAG', nullable=False),
    sa.Column('on_outside_geofence', sa.Enum('ALLOW', 'FLAG', 'REJECT', name='on_outside_geofence', native_enum=False, create_constraint=True, length=32), server_default='FLAG', nullable=False),
    sa.Column('on_impossible_travel', sa.Enum('ALLOW', 'FLAG', 'REJECT', name='on_impossible_travel', native_enum=False, create_constraint=True, length=32), server_default='FLAG', nullable=False),
    sa.Column('on_clock_skew', sa.Enum('ALLOW', 'FLAG', 'REJECT', name='on_clock_skew', native_enum=False, create_constraint=True, length=32), server_default='FLAG', nullable=False),
    sa.Column('on_qr_fail', sa.Enum('ALLOW', 'FLAG', 'REJECT', name='on_qr_fail', native_enum=False, create_constraint=True, length=32), server_default='FLAG', nullable=False),
    sa.Column('max_accuracy_m', sa.Integer(), server_default='100', nullable=False),
    sa.Column('max_fix_age_s', sa.Integer(), server_default='60', nullable=False),
    sa.Column('challenge_ttl_s', sa.Integer(), server_default='90', nullable=False),
    sa.Column('max_travel_speed_kmh', sa.Integer(), server_default='200', nullable=False),
    sa.Column('max_clock_skew_s', sa.Integer(), server_default='300', nullable=False),
    sa.Column('flagged_counts_before_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('challenge_ttl_s BETWEEN 15 AND 600', name=op.f('ck_attendance_policies_challenge_ttl_range')),
    sa.CheckConstraint('max_accuracy_m BETWEEN 5 AND 2000', name=op.f('ck_attendance_policies_max_accuracy_range')),
    sa.CheckConstraint('max_clock_skew_s BETWEEN 0 AND 86400', name=op.f('ck_attendance_policies_max_clock_skew_range')),
    sa.CheckConstraint('max_fix_age_s BETWEEN 5 AND 600', name=op.f('ck_attendance_policies_max_fix_age_range')),
    sa.CheckConstraint('max_travel_speed_kmh BETWEEN 10 AND 2000', name=op.f('ck_attendance_policies_max_speed_range')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_attendance_policies_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attendance_policies_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_attendance_policies_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_policies')),
    sa.UniqueConstraint('organization_id', 'location_id', name=op.f('uq_attendance_policies_organization_id_location_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_table('employees',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('work_schedule_id', sa.UUID(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'SUSPENDED', 'TERMINATED', name='employment_status', native_enum=False, create_constraint=True, length=32), server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments')),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name=op.f('fk_employees_manager_id_managers')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employees_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users')),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], name=op.f('fk_employees_work_schedule_id_work_schedules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('organization_id', 'employee_code', name=op.f('uq_employees_organization_id_employee_code')),
    sa.UniqueConstraint('user_id', name=op.f('uq_employees_user_id'))
    )
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    # managers <-> employees reference each other, so this FK is added after both tables exist.
    op.create_foreign_key(op.f('fk_managers_employee_id_employees'), 'managers', 'employees', ['employee_id'], ['id'])
    op.create_table('holidays',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_holidays_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_holidays_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays')),
    sa.UniqueConstraint('organization_id', 'location_id', 'holiday_date', name=op.f('uq_holidays_organization_id_location_id_holiday_date'), postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_holidays_holiday_date'), 'holidays', ['holiday_date'], unique=False)
    op.create_table('qr_sessions',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('display_label', sa.String(length=100), nullable=False),
    sa.Column('display_credential_hash', sa.String(length=64), nullable=True),
    sa.Column('key_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rotation_seconds', sa.Integer(), server_default='30', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rotation_seconds BETWEEN 15 AND 86400', name=op.f('ck_qr_sessions_rotation_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_qr_sessions_created_by_users')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_qr_sessions_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_sessions')),
    sa.UniqueConstraint('display_credential_hash', name=op.f('uq_qr_sessions_display_credential_hash'))
    )
    op.create_index(op.f('ix_qr_sessions_location_id'), 'qr_sessions', ['location_id'], unique=False)
    op.create_table('report_runs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('report_setting_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'EMPLOYEE', 'LOCATION', 'DEPARTMENT', 'MANAGER', 'LATE', 'ABSENCE', 'SUSPICIOUS', name='report_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('format', sa.Enum('EXCEL', 'PDF', name='format', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='status', native_enum=False, create_constraint=True, length=32), server_default='QUEUED', nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_report_runs_organization_id_organizations')),
    sa.ForeignKeyConstraint(['report_setting_id'], ['report_settings.id'], name=op.f('fk_report_runs_report_setting_id_report_settings')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_report_runs_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_runs'))
    )
    op.create_index('ix_report_runs_org_created', 'report_runs', ['organization_id', 'created_at'], unique=False)
    op.create_table('attendance',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_start', sa.Time(), nullable=True),
    sa.Column('scheduled_end', sa.Time(), nullable=True),
    sa.Column('grace_minutes', sa.Integer(), nullable=True),
    sa.Column('early_departure_minutes', sa.Integer(), nullable=True),
    sa.Column('first_check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('arrival_status', sa.Enum('PRESENT', 'LATE', name='arrival_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('departure_status', sa.Enum('CHECKED_OUT', 'EARLY_DEPARTURE', 'MISSING_CHECKOUT', name='departure_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('day_status', sa.Enum('PRESENT', 'LATE', 'ABSENT', 'PENDING_REVIEW', 'ON_LEAVE', 'HOLIDAY', 'NON_WORKING_DAY', name='day_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'SUSPICIOUS', 'PENDING_REVIEW', 'REJECTED', name='verification_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('is_manually_adjusted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('worked_minutes >= 0', name=op.f('ck_attendance_worked_minutes_positive')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_employee_id_employees')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_attendance_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('employee_id', 'attendance_date', name=op.f('uq_attendance_employee_id_attendance_date'))
    )
    op.create_index(op.f('ix_attendance_attendance_date'), 'attendance', ['attendance_date'], unique=False)
    op.create_index('ix_attendance_location_date', 'attendance', ['location_id', 'attendance_date'], unique=False)
    op.create_index('ix_attendance_needs_attention', 'attendance', ['verification_status'], unique=False, postgresql_where=sa.text("verification_status <> 'VERIFIED'"))
    op.create_table('device_registrations',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('install_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=16), server_default='android', nullable=False),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('key_algorithm', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'ACTIVE', 'REJECTED', 'DEACTIVATED', 'REREGISTRATION_REQUIRED', name='device_status', native_enum=False, create_constraint=True, length=32), server_default='PENDING_APPROVAL', nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('last_integrity_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_device_registrations_approved_by_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_device_registrations_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_registrations'))
    )
    op.create_index(op.f('ix_device_registrations_employee_id'), 'device_registrations', ['employee_id'], unique=False)
    op.create_index('ix_device_registrations_status', 'device_registrations', ['status'], unique=False)
    op.create_index('uq_device_registrations_fingerprint_in_use', 'device_registrations', ['device_fingerprint'], unique=True, postgresql_where=sa.text("status IN ('PENDING_APPROVAL', 'ACTIVE')"))
    op.create_index('uq_device_registrations_one_active_per_employee', 'device_registrations', ['employee_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('employee_locations',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('valid_from', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name=op.f('ck_employee_locations_valid_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_employee_locations_created_by_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_locations_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_employee_locations_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_locations')),
    sa.UniqueConstraint('employee_id', 'location_id', name=op.f('uq_employee_locations_employee_id_location_id'))
    )
    op.create_index(op.f('ix_employee_locations_location_id'), 'employee_locations', ['location_id'], unique=False)
    op.create_index('uq_employee_locations_one_primary', 'employee_locations', ['employee_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('leave_records',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.Enum('ANNUAL', 'SICK', 'MATERNITY', 'PATERNITY', 'OFFICIAL_DUTY', 'UNPAID', 'OTHER', name='leave_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'CANCELLED', name='leave_status', native_enum=False, create_constraint=True, length=32), server_default='APPROVED', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_leave_records_end_after_start')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_records_employee_id_employees')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_leave_records_recorded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_records'))
    )
    op.create_index('ix_leave_records_employee_dates', 'leave_records', ['employee_id', 'start_date', 'end_date'], unique=False)
    op.create_table('attendance_adjustments',
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], name=op.f('fk_attendance_adjustments_attendance_id_attendance')),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_attendance_adjustments_changed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_adjustments'))
    )
    op.create_index(op.f('ix_attendance_adjustments_attendance_id'), 'attendance_adjustments', ['attendance_id'], unique=False)
    op.create_table('attendance_challenges',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('device_registration_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CHECK_IN', 'CHECK_OUT', name='action', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('nonce_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at > issued_at', name=op.f('ck_attendance_challenges_expiry_after_issue')),
    sa.ForeignKeyConstraint(['device_registration_id'], ['device_registrations.id'], name=op.f('fk_attendance_challenges_device_registration_id_device_registrations')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_challenges_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_challenges')),
    sa.UniqueConstraint('nonce_hash', name=op.f('uq_attendance_challenges_nonce_hash'))
    )
    op.create_index(op.f('ix_attendance_challenges_employee_id'), 'attendance_challenges', ['employee_id'], unique=False)
    op.create_index('ix_attendance_challenges_expires_at', 'attendance_challenges', ['expires_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('client_type', sa.Enum('MOBILE', 'WEB', name='client_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('device_registration_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=50), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_registration_id'], ['device_registrations.id'], name=op.f('fk_refresh_tokens_device_registration_id_device_registrations')),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('attendance_events',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('attendance_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('CHECK_IN', 'CHECK_OUT', name='event_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('client_request_id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=True),
    sa.Column('device_registration_id', sa.UUID(), nullable=True),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('accuracy_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fix_age_ms', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('result', sa.Enum('ACCEPTED', 'FLAGGED', 'REJECTED', name='result', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('employee_message_code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accuracy_m IS NULL OR accuracy_m >= 0', name=op.f('ck_attendance_events_accuracy_positive')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_attendance_events_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_attendance_events_longitude_range')),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], name=op.f('fk_attendance_events_attendance_id_attendance')),
    sa.ForeignKeyConstraint(['challenge_id'], ['attendance_challenges.id'], name=op.f('fk_attendance_events_challenge_id_attendance_challenges')),
    sa.ForeignKeyConstraint(['device_registration_id'], ['device_registrations.id'], name=op.f('fk_attendance_events_device_registration_id_device_registrations')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_events_employee_id_employees')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_attendance_events_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_events')),
    sa.UniqueConstraint('challenge_id', name=op.f('uq_attendance_events_challenge_id')),
    sa.UniqueConstraint('employee_id', 'client_request_id', name=op.f('uq_attendance_events_employee_id_client_request_id'))
    )
    op.create_index(op.f('ix_attendance_events_attendance_id'), 'attendance_events', ['attendance_id'], unique=False)
    op.create_index('ix_attendance_events_employee_time', 'attendance_events', ['employee_id', 'server_received_at'], unique=False)
    op.create_index('ix_attendance_events_location_time', 'attendance_events', ['location_id', 'server_received_at'], unique=False)
    op.create_index('ix_attendance_events_result', 'attendance_events', ['result'], unique=False)
    op.create_table('attendance_event_reviews',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='decision', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['attendance_events.id'], name=op.f('fk_attendance_event_reviews_event_id_attendance_events')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_attendance_event_reviews_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_event_reviews')),
    sa.UniqueConstraint('event_id', name=op.f('uq_attendance_event_reviews_event_id'))
    )
    op.create_table('attendance_sessions',
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('check_in_event_id', sa.UUID(), nullable=False),
    sa.Column('check_out_event_id', sa.UUID(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'MISSING_CHECKOUT', name='session_status', native_enum=False, create_constraint=True, length=32), server_default='OPEN', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_out_at IS NULL OR check_out_at >= check_in_at', name=op.f('ck_attendance_sessions_out_after_in')),
    sa.CheckConstraint('worked_minutes >= 0', name=op.f('ck_attendance_sessions_worked_minutes_positive')),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], name=op.f('fk_attendance_sessions_attendance_id_attendance'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['check_in_event_id'], ['attendance_events.id'], name=op.f('fk_attendance_sessions_check_in_event_id_attendance_events')),
    sa.ForeignKeyConstraint(['check_out_event_id'], ['attendance_events.id'], name=op.f('fk_attendance_sessions_check_out_event_id_attendance_events')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_sessions_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_sessions')),
    sa.UniqueConstraint('check_in_event_id', name=op.f('uq_attendance_sessions_check_in_event_id')),
    sa.UniqueConstraint('check_out_event_id', name=op.f('uq_attendance_sessions_check_out_event_id'))
    )
    op.create_index(op.f('ix_attendance_sessions_attendance_id'), 'attendance_sessions', ['attendance_id'], unique=False)
    op.create_index('uq_attendance_sessions_one_open', 'attendance_sessions', ['employee_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('attendance_verification',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('geofence', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='geofence', native_enum=False, create_constraint=True, length=32), server_default='NOT_APPLICABLE', nullable=False),
    sa.Column('gps_accuracy', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='gps_accuracy', native_enum=False, create_constraint=True, length=32), server_default='NOT_APPLICABLE', nullable=False),
    sa.Column('mock_location', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='mock_location', native_enum=False, create_constraint=True, length=32), server_default='NOT_APPLICABLE', nullable=False),
    sa.Column('play_integrity', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='play_integrity', native_enum=False, create_constraint=True, length=32), server_default='NOT_APPLICABLE', nullable=False),
    sa.Column('location_age', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='location_age', native_enum=False, create_constraint=True, length=32), server_default='NOT_APPLICABLE', nullable=False),
    sa.Column('timestamp_check', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='timestamp_check', native_enum=False, create_constraint=True, length=32), server_default='NOT_APPLICABLE', nullable=False),
    sa.Column('replay_check', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='replay_check', native_enum=False, create_constraint=True, length=32), server_default='NOT_APPLICABLE', nullable=False),
    sa.Column('movement_check', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='movement_check', native_enum=False, create_constraint=True, length=32), server_default='NOT_APPLICABLE', nullable=False),
    sa.Column('qr_check', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='qr_check', native_enum=False, create_constraint=True, length=32), server_default='NOT_APPLICABLE', nullable=False),
    sa.Column('device_check', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='device_check', native_enum=False, create_constraint=True, length=32), server_default='NOT_APPLICABLE', nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('final_result', sa.Enum('ACCEPTED', 'FLAGGED', 'REJECTED', name='final_result', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name=op.f('ck_attendance_verification_risk_score_range')),
    sa.ForeignKeyConstraint(['event_id'], ['attendance_events.id'], name=op.f('fk_attendance_verification_event_id_attendance_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_verification')),
    sa.UniqueConstraint('event_id', name=op.f('uq_attendance_verification_event_id'))
    )
    op.create_table('security_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('attendance_event_id', sa.UUID(), nullable=True),
    sa.Column('device_registration_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_event_id'], ['attendance_events.id'], name=op.f('fk_security_events_attendance_event_id_attendance_events')),
    sa.ForeignKeyConstraint(['device_registration_id'], ['device_registrations.id'], name=op.f('fk_security_events_device_registration_id_device_registrations')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_security_events_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_security_events_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_security_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index('ix_security_events_created_at', 'security_events', ['created_at'], unique=False)
    op.create_index('ix_security_events_employee_time', 'security_events', ['employee_id', 'created_at'], unique=False)
    op.create_index('ix_security_events_type_time', 'security_events', ['event_type', 'created_at'], unique=False)
    op.create_table('verification_signals',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('QR', 'NFC', 'BLE_BEACON', 'SELFIE', name='signal_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'WARN', 'FAIL', 'NOT_APPLICABLE', name='result', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['attendance_verification.id'], name=op.f('fk_verification_signals_verification_id_attendance_verification')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_signals'))
    )
    op.create_index(op.f('ix_verification_signals_verification_id'), 'verification_signals', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_managers_employee_id_employees'), 'managers', type_='foreignkey')
    op.drop_index(op.f('ix_verification_signals_verification_id'), table_name='verification_signals')
    op.drop_table('verification_signals')
    op.drop_index('ix_security_events_type_time', table_name='security_events')
    op.drop_index('ix_security_events_employee_time', table_name='security_events')
    op.drop_index('ix_security_events_created_at', table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('attendance_verification')
    op.drop_index('uq_attendance_sessions_one_open', table_name='attendance_sessions', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index(op.f('ix_attendance_sessions_attendance_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_table('attendance_event_reviews')
    op.drop_index('ix_attendance_events_result', table_name='attendance_events')
    op.drop_index('ix_attendance_events_location_time', table_name='attendance_events')
    op.drop_index('ix_attendance_events_employee_time', table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_attendance_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_attendance_challenges_expires_at', table_name='attendance_challenges')
    op.drop_index(op.f('ix_attendance_challenges_employee_id'), table_name='attendance_challenges')
    op.drop_table('attendance_challenges')
    op.drop_index(op.f('ix_attendance_adjustments_attendance_id'), table_name='attendance_adjustments')
    op.drop_table('attendance_adjustments')
    op.drop_index('ix_leave_records_employee_dates', table_name='leave_records')
    op.drop_table('leave_records')
    op.drop_index('uq_employee_locations_one_primary', table_name='employee_locations', postgresql_where=sa.text('is_primary'))
    op.drop_index(op.f('ix_employee_locations_location_id'), table_name='employee_locations')
    op.drop_table('employee_locations')
    op.drop_index('uq_device_registrations_one_active_per_employee', table_name='device_registrations', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('uq_device_registrations_fingerprint_in_use', table_name='device_registrations', postgresql_where=sa.text("status IN ('PENDING_APPROVAL', 'ACTIVE')"))
    op.drop_index('ix_device_registrations_status', table_name='device_registrations')
    op.drop_index(op.f('ix_device_registrations_employee_id'), table_name='device_registrations')
    op.drop_table('device_registrations')
    op.drop_index('ix_attendance_needs_attention', table_name='attendance', postgresql_where=sa.text("verification_status <> 'VERIFIED'"))
    op.drop_index('ix_attendance_location_date', table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_date'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('ix_report_runs_org_created', table_name='report_runs')
    op.drop_table('report_runs')
    op.drop_index(op.f('ix_qr_sessions_location_id'), table_name='qr_sessions')
    op.drop_table('qr_sessions')
    op.drop_index(op.f('ix_holidays_holiday_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('attendance_policies')
    op.drop_table('work_schedule_days')
    op.drop_index(op.f('ix_report_settings_organization_id'), table_name='report_settings')
    op.drop_table('report_settings')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('managers')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_branch_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index('ix_audit_logs_object', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_work_schedules_organization_id'), table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('retention_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_branches_organization_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_table('organizations')
    # ### end Alembic commands ###
