"""user token version

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 10:56:01.773983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_events', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # security_events.organization_id intentionally stays NULLable: rows recorded without an
    # organization (failed logins for unknown names) are append-only evidence and can't be
    # deleted or changed, so making the column NOT NULL again would fail.
    # ### end Alembic commands ###
