"""session review state

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 12:11:55.671838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('pending_review', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###
    # Allow the new session status REJECTED (Alembic doesn't detect CHECK constraint changes).
    op.drop_constraint(op.f('ck_attendance_sessions_session_status'), 'attendance_sessions', type_='check')
    op.create_check_constraint(
        op.f('ck_attendance_sessions_session_status'), 'attendance_sessions',
        "status IN ('OPEN', 'CLOSED', 'MISSING_CHECKOUT', 'REJECTED')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_attendance_sessions_session_status'), 'attendance_sessions', type_='check')
    # The old schema has no REJECTED status. Rejected sessions become MISSING_CHECKOUT there
    # (the nearest old meaning); the HR decision itself stays in attendance_event_reviews.
    op.execute("UPDATE attendance_sessions SET status = 'MISSING_CHECKOUT' WHERE status = 'REJECTED'")
    op.create_check_constraint(
        op.f('ck_attendance_sessions_session_status'), 'attendance_sessions',
        "status IN ('OPEN', 'CLOSED', 'MISSING_CHECKOUT')",
    )
    op.drop_column('attendance_sessions', 'pending_review')
    # ### end Alembic commands ###
