"""email outbox

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-03 02:36:16.751370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

APP_ROLE = "attendance_app"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_outbox',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('NOTIFICATION', 'REPORT', 'TEST', name='category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('to_address', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', name='status', native_enum=False, create_constraint=True, length=32), server_default='QUEUED', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('report_setting_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_email_outbox_organization_id_organizations')),
    sa.ForeignKeyConstraint(['report_setting_id'], ['report_settings.id'], name=op.f('fk_email_outbox_report_setting_id_report_settings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_outbox_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_outbox'))
    )
    op.create_index('ix_email_outbox_due', 'email_outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_email_outbox_org_created', 'email_outbox', ['organization_id', 'created_at'], unique=False)
    op.create_index('uq_email_outbox_dedupe', 'email_outbox', ['to_address', 'dedupe_key'], unique=True, postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.create_table('email_attachments',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=150), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email_outbox.id'], name=op.f('fk_email_attachments_email_id_email_outbox'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_attachments'))
    )
    op.create_index(op.f('ix_email_attachments_email_id'), 'email_attachments', ['email_id'], unique=False)
    op.add_column('notifications', sa.Column('dedupe_key', sa.String(length=200), nullable=True))
    op.create_index('uq_notifications_user_dedupe', 'notifications', ['user_id', 'dedupe_key'], unique=True, postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.add_column('report_settings', sa.Column('last_scheduled_for', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # The API's database role may read/write the new tables (skipped if the role doesn't exist).
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE ON email_outbox, email_attachments TO {APP_ROLE};
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_settings', 'last_scheduled_for')
    op.drop_index('uq_notifications_user_dedupe', table_name='notifications', postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.drop_column('notifications', 'dedupe_key')
    op.drop_index(op.f('ix_email_attachments_email_id'), table_name='email_attachments')
    op.drop_table('email_attachments')
    op.drop_index('uq_email_outbox_dedupe', table_name='email_outbox', postgresql_where=sa.text('dedupe_key IS NOT NULL'))
    op.drop_index('ix_email_outbox_org_created', table_name='email_outbox')
    op.drop_index('ix_email_outbox_due', table_name='email_outbox')
    op.drop_table('email_outbox')
    # ### end Alembic commands ###
