"""security monitoring

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-04 19:03:08.726541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

APP_ROLE = "attendance_app"

OLD_EVENTS = ["LATE_EMPLOYEE", "SUSPICIOUS_CHECK_IN", "REJECTED_CHECK_IN", "MISSING_CHECKOUT", "HIGH_ABSENCE",
              "REPORT_GENERATED", "DEVICE_APPROVAL_REQUESTED"]
NEW_EVENTS = OLD_EVENTS + ["SECURITY_ALERT"]


def _event_checks(events: list[str]) -> None:
    allowed = ", ".join(f"'{e}'" for e in events)
    for table in ("notifications", "notification_settings"):
        name = f"ck_{table}_event_type"
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT {name}")
        op.execute(f"ALTER TABLE {table} ADD CONSTRAINT {name} CHECK (event_type IN ({allowed}))")


# Same as 0002, plus ONE narrow exception for data retention: the retention job (owner role
# only, after SET LOCAL app.allow_redact = 'on') may clear the GPS coordinates of an
# attendance event - and change nothing else.
PREVENT_WITH_REDACTION = """
CREATE OR REPLACE FUNCTION prevent_modification() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' AND current_setting('app.allow_purge', true) = 'on' THEN
        RETURN OLD;
    END IF;
    -- Nested IFs: PL/pgSQL may evaluate every part of an AND, and other tables have no
    -- latitude column.
    IF TG_OP = 'UPDATE' AND TG_TABLE_NAME = 'attendance_events'
       AND current_setting('app.allow_redact', true) = 'on' THEN
        IF (to_jsonb(NEW) ->> 'latitude') IS NULL AND (to_jsonb(NEW) ->> 'longitude') IS NULL
           AND (to_jsonb(NEW) ->> 'accuracy_m') IS NULL
           AND (to_jsonb(NEW) - 'latitude' - 'longitude' - 'accuracy_m')
             = (to_jsonb(OLD) - 'latitude' - 'longitude' - 'accuracy_m') THEN
            RETURN NEW;
        END IF;
    END IF;
    RAISE EXCEPTION 'Table % is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$;
"""

PREVENT_ORIGINAL = """
CREATE OR REPLACE FUNCTION prevent_modification() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' AND current_setting('app.allow_purge', true) = 'on' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'Table % is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$;
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_checkpoints',
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('last_seq', sa.BigInteger(), nullable=True),
    sa.Column('last_hash', sa.String(length=64), nullable=True),
    sa.Column('rows_checked', sa.BigInteger(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('problem_seq', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_checkpoints'))
    )
    op.create_table('security_alerts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('subject_key', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='status', native_enum=False, create_constraint=True, length=32), server_default='OPEN', nullable=False),
    sa.Column('handled_by', sa.UUID(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_security_alerts_employee_id_employees')),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], name=op.f('fk_security_alerts_handled_by_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_security_alerts_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_alerts'))
    )
    op.create_index('ix_security_alerts_org_status', 'security_alerts', ['organization_id', 'status', 'last_seen_at'], unique=False)
    op.create_index('uq_security_alerts_active', 'security_alerts', ['organization_id', 'rule', 'subject_key'], unique=True, postgresql_where=sa.text("status <> 'RESOLVED'"))
    # ### end Alembic commands ###
    _event_checks(NEW_EVENTS)
    op.execute(PREVENT_WITH_REDACTION)
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                GRANT SELECT, INSERT, UPDATE ON security_alerts TO {APP_ROLE};
                GRANT SELECT, INSERT ON audit_checkpoints TO {APP_ROLE};
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    """Downgrade schema. Security-alert notifications are removed (the old schema has no such type)."""
    op.execute(PREVENT_ORIGINAL)
    op.execute("DELETE FROM notifications WHERE event_type = 'SECURITY_ALERT'")
    op.execute("DELETE FROM notification_settings WHERE event_type = 'SECURITY_ALERT'")
    _event_checks(OLD_EVENTS)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_security_alerts_active', table_name='security_alerts', postgresql_where=sa.text("status <> 'RESOLVED'"))
    op.drop_index('ix_security_alerts_org_status', table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_table('audit_checkpoints')
    # ### end Alembic commands ###
